// <auto-generated />
using System;
using BookstoreApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookstoreApp.Server.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20260119133027_NewSeedData")]
    partial class NewSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookstoreApp.Server.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Books_CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique()
                        .HasDatabaseName("IX_Books_ISBN");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Books_Status");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic American novel set in the Jazz Age, exploring themes of decadence, idealism, and social upheaval.",
                            ISBN = "978-0743273565",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/960px-The_Great_Gatsby_Cover_1925_Retouched.jpg",
                            Language = "English",
                            PageCount = 180,
                            Price = 15.99m,
                            PublishDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scribner",
                            Status = 0,
                            StockQuantity = 50,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A gripping tale of racial injustice and childhood innocence in the American South.",
                            ISBN = "978-0061120084",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/960px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg",
                            Language = "English",
                            PageCount = 324,
                            Price = 18.99m,
                            PublishDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Harper Perennial",
                            Status = 0,
                            StockQuantity = 35,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dystopian masterpiece about surveillance, propaganda, and totalitarianism.",
                            ISBN = "978-0451524935",
                            ImageUrl = "https://cdn.kobo.com/book-images/698a1326-f8b7-4664-8f34-75f6633e816e/1200/1200/False/13xLRb-vHz2DfdgvhkjkHg.jpg",
                            Language = "English",
                            PageCount = 328,
                            Price = 14.99m,
                            PublishDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Signet Classic",
                            Status = 0,
                            StockQuantity = 60,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Yuval Noah Harari",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An exploration of how Homo sapiens came to dominate the world.",
                            ISBN = "978-0062316097",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Sapiens-_A_Brief_History_of_Humankind.png/960px-Sapiens-_A_Brief_History_of_Humankind.png",
                            Language = "English",
                            PageCount = 443,
                            Price = 24.99m,
                            PublishDate = new DateTime(2015, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Harper",
                            Status = 0,
                            StockQuantity = 40,
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert C. Martin",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A guide to writing clean, maintainable code that works.",
                            ISBN = "978-0132350884",
                            ImageUrl = "https://m.media-amazon.com/images/I/51E2055ZGUL._SL1000_.jpg",
                            Language = "English",
                            PageCount = 464,
                            Price = 44.99m,
                            PublishDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Prentice Hall",
                            Status = 0,
                            StockQuantity = 25,
                            Title = "Clean Code: A Handbook of Agile Software Craftsmanship"
                        },
                        new
                        {
                            Id = 6,
                            Author = "J.K. Rowling",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The first book in the beloved Harry Potter series about a young wizard's adventures.",
                            ISBN = "978-0439708180",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/a0/Harry_Potter_and_the_Prisoner_of_Azkaban.jpg",
                            Language = "English",
                            PageCount = 309,
                            Price = 12.99m,
                            PublishDate = new DateTime(1998, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scholastic",
                            Status = 0,
                            StockQuantity = 100,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Cormac McCarthy",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A post-apocalyptic journey of a father and son through a devastated world.",
                            ISBN = "978-0307474278",
                            ImageUrl = "https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg",
                            Language = "English",
                            PageCount = 287,
                            Price = 16.99m,
                            PublishDate = new DateTime(2006, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Vintage",
                            Status = 0,
                            StockQuantity = 30,
                            Title = "The Road"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Tara Westover",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A memoir about growing up without formal education and the pursuit of knowledge.",
                            ISBN = "978-0812981605",
                            ImageUrl = "https://cdn.penguin.co.uk/dam-assets/books/9780099511021/9780099511021-jacket-large.jpg",
                            Language = "English",
                            PageCount = 352,
                            Price = 18.99m,
                            PublishDate = new DateTime(2018, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Random House",
                            Status = 0,
                            StockQuantity = 28,
                            Title = "Educated"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Siddhartha Mukherjee",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A comprehensive exploration of the history and future of genetic research.",
                            ISBN = "978-0393354324",
                            ImageUrl = "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1452452965i/27276428.jpg",
                            Language = "English",
                            PageCount = 608,
                            Price = 21.99m,
                            PublishDate = new DateTime(2016, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Scribner",
                            Status = 0,
                            StockQuantity = 22,
                            Title = "The Gene: An Intimate History"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Andrew Lock",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A practical guide to building modern web applications with ASP.NET Core.",
                            ISBN = "978-1617294532",
                            ImageUrl = "https://images.manning.com/book/9/37efddf-eba2-42ec-bdca-744dc3de0d1e/Lock-3ed-HI.png",
                            Language = "English",
                            PageCount = 825,
                            Price = 49.99m,
                            PublishDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Manning",
                            Status = 0,
                            StockQuantity = 18,
                            Title = "ASP.NET Core in Action"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Michelle Obama",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An inspiring memoir by the former First Lady of the United States.",
                            ISBN = "978-1501124020",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/09/Becoming_%28Michelle_Obama_book%29.jpg",
                            Language = "English",
                            PageCount = 448,
                            Price = 20.99m,
                            PublishDate = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Crown",
                            Status = 0,
                            StockQuantity = 35,
                            Title = "Becoming"
                        },
                        new
                        {
                            Id = 12,
                            Author = "George R. R. Martin",
                            CategoryId = 6,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The first book in the epic fantasy series A Song of Ice and Fire.",
                            ISBN = "978-0553573404",
                            ImageUrl = "https://m.media-amazon.com/images/I/71Jzezm8CBL._AC_UF1000,1000_QL80_.jpg",
                            Language = "English",
                            PageCount = 694,
                            Price = 17.99m,
                            PublishDate = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Bantam",
                            Status = 0,
                            StockQuantity = 70,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Alex Michaelides",
                            CategoryId = 7,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A psychological thriller about a woman who stops speaking after a tragic event.",
                            ISBN = "978-0385545969",
                            ImageUrl = "https://cdn.waterstones.com/bookjackets/large/9781/4091/9781409181637.jpg",
                            Language = "English",
                            PageCount = 336,
                            Price = 15.99m,
                            PublishDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Celadon Books",
                            Status = 0,
                            StockQuantity = 42,
                            Title = "The Silent Patient"
                        });
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique()
                        .HasDatabaseName("IX_CartItems_UserId_BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Categories_Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fiction novels and stories",
                            IsActive = true,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Real-world topics and information",
                            IsActive = true,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scientific books and research",
                            IsActive = true,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Technology and programming books",
                            IsActive = true,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Life stories and biographies",
                            IsActive = true,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fantasy and magical worlds",
                            IsActive = true,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mystery and thriller books",
                            IsActive = true,
                            Name = "Mystery"
                        });
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.InventoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("QuantityAfter")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("IX_InventoryLogs_BookId");

                    b.HasIndex("LoggedAt")
                        .HasDatabaseName("IX_InventoryLogs_LoggedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_InventoryLogs_UserId");

                    b.ToTable("InventoryLogs");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShippingPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderDate")
                        .HasDatabaseName("IX_Orders_OrderDate");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_OrderNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Orders_UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtOrder")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_OrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Payments_Status");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Admin Street, System City",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@bookstore.com",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$c0yfTXhEQmQsrOxqmqb4XeoypY9u5Sc1IieQ8UL3vSdrUUrwYUX.i",
                            PhoneNumber = "555-0001",
                            Role = 2,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Ba Dinh District, Hanoi",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "minh.nguyen@gmail.com",
                            FullName = "Nguyen Minh Quan",
                            IsActive = true,
                            PasswordHash = "$2a$11$K/HrNSGeHKv.i/HPtCLVkeejiSsmypCj5ZANC7RU8JwOFsifQRCj6",
                            PhoneNumber = "0903123456",
                            Role = 0,
                            UserName = "minh.nguyen"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Warehouse Center, CA",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alex.morgan@bookstore.com",
                            FullName = "Alex Morgan",
                            IsActive = true,
                            PasswordHash = "$2a$11$xNNVXHUdt0GdZiJx2WhcAOpK6AjnwZw938EMMzY.B5F9YcTVqlz8G",
                            PhoneNumber = "555-3012",
                            Role = 1,
                            UserName = "alex.morgan"
                        });
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique()
                        .HasDatabaseName("IX_WishlistItems_UserId_BookId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Book", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Books_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.CartItem", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.Book", "Book")
                        .WithMany("CartItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Books");

                    b.HasOne("BookstoreApp.Server.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Users");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.InventoryLog", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.Book", "Book")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryLogs_Books");

                    b.HasOne("BookstoreApp.Server.Models.User", "User")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_InventoryLogs_Users");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Order", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.OrderItem", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.Book", "Book")
                        .WithMany("OrderItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Books");

                    b.HasOne("BookstoreApp.Server.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderItems_Orders");

                    b.Navigation("Book");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Payment", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("BookstoreApp.Server.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Payment");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.WishlistItem", b =>
                {
                    b.HasOne("BookstoreApp.Server.Models.Book", "Book")
                        .WithMany("WishlistItems")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WishlistItems_Books");

                    b.HasOne("BookstoreApp.Server.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WishlistItems_Users");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Book", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderItems");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BookstoreApp.Server.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InventoryLogs");

                    b.Navigation("Orders");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
